---

- include_tasks:
    file: disable-one-default.yaml
  loop:
    - AutomaticCheckEnabled
    - AutomaticDownload
    - AutomaticallyInstallMacOSUpdates
    - ConfigDataInstall
    - CriticalUpdateInstall
