---

# Create or update project runners. The logic is different depending on whether we are creating a
# new runner or updating an existing one. We detect new registrations by the absence of a registration file at
# /etc/gitlab-runner/registration/project.<project-id>.json
#
# ** New Runners **
#
# Creating a new runner returns output containing the runner token, which is required later when constructing
# the config.toml file. The output is saved in a per-project registration file at /etc/gitlab-runner/registration/project.<project-id>.json.
#
# ** Existing Runners **
#
# Updating an existing runner does NOT return the same information as creating one. In particular, the runner token
# is NOT returned from this call.

- name: Register owned runner
  become: true
  block:
    - name: Check if owned runner is already registered
      stat:
        path: /etc/gitlab-runner/registration/owned.json
      register: owned_runner_registered

    - name: Register owned runner, or update it
      gitlab_runner:
        description: "{{ gitlab_runner_description }}"
        api_token: "{{ gitlab_runner_access_token | trim }}"
        registration_token: "{{ gitlab_runner_registration_token | trim }}"
        access_level: not_protected
        api_url: https://gitlab.com/
        owned: true
        state: present
        active: true
        tag_list: "{{ gitlab_runner_tags + gitlab_runner_host_tags }}"
        run_untagged: false
        locked: false
      register: owned_runner_registration

    - name: Record new owned registration
      copy:
        content: "{{ owned_runner_registration.runner }}"
        dest: /etc/gitlab-runner/registration/owned.json
        owner: root
        group: admin
        mode: 'u=rw,g=,o='
      when: not owned_runner_registered.stat.exists

    - name: Read owned runner registration
      command: cat /etc/gitlab-runner/registration/owned.json
      register: runner_owned_registration_cmd
      changed_when: false

    - name: Set owned runner registration
      set_fact:
        runner_owned_registration: "{{ runner_owned_registration_cmd.stdout | from_json }}"

- name: Create runner config file
  become: true
  template:
    src: config.toml
    dest: /etc/gitlab-runner/config.toml
    owner: root
    group: admin
    mode: 'u=rw,g=,o='
