---

# Create or update project runners. The logic is different depending on whether we are creating a
# new runner or updating an existing one. We detect new registrations by the absence of a registration file at
# /etc/gitlab-runner/registration/project.<project-id>.json
#
# ** New Runners **
#
# Creating a new runner returns output containing the runner token, which is required later when constructing
# the config.toml file. The output is saved in a per-project registration file at /etc/gitlab-runner/registration/project.<project-id>.json.
#
# ** Existing Runners **
#
# Updating an existing runner does NOT return the same information as creating one. In particular, the runner token
# is NOT returned from this call.


- name: Register per-project runners
  become: true
  block:
    - name: Check if per-project runners are already registered
      stat:
        path: /etc/gitlab-runner/registration/project.{{ item.id }}.json
      loop: "{{ gitlab_macos_projects }}"
      loop_control:
        label: "{{ item.name }}"
        index_var: index
      register: runner_registered

    - name: Register per-project runners, or update them
      gitlab_runner:
        description: "{{ gitlab_runner_description }}"
        api_token: "{{ item.access_token | trim }}"
        registration_token: "{{ item.registration_token | trim }}"
        project: "{{ item.id }}"
        access_level: not_protected
        api_url: https://gitlab.com/
        state: present
        active: true
        tag_list: "{{ gitlab_runner_tags + gitlab_runner_host_tags }}"
        run_untagged: false
        locked: false
      loop: "{{ gitlab_macos_projects }}"
      loop_control:
        label: "{{ item.name }}"
        index_var: index
      register: runner_registration

    - name: Record per-project registrations (new runners only)
      copy:
        content: "{{ runner_registration.results[index].runner }}"
        dest: /etc/gitlab-runner/registration/project.{{ item.id }}.json
        owner: root
        group: admin
        mode: 'u=rw,g=,o='
      loop: "{{ gitlab_macos_projects }}"
      loop_control:
        label: "{{ item.name }}"
        index_var: index
      when: not runner_registered.results[index].stat.exists

    - name: Read all per-project runner registrations, both new and existing
      command: cat /etc/gitlab-runner/registration/project.{{ item.id }}.json
      loop: "{{ gitlab_macos_projects }}"
      loop_control:
        label: "{{ item.name }}"
      register: runner_per_project_registrations_cmd
      changed_when: false

    - name: Set per-project runner registrations
      set_fact:
        runner_per_project_registrations: "{{ runner_per_project_registrations|default([]) + [runner_per_project_registrations_cmd.results[index].stdout | from_json] }}"
      loop: "{{ gitlab_macos_projects }}"
      loop_control:
        label: "{{ item.name }}"
        index_var: index

- name: Create runner config file
  become: true
  template:
    src: config.toml
    dest: /etc/gitlab-runner/config.toml
    owner: root
    group: admin
    mode: 'u=rw,g=,o='
