---

- name: Register per-project runners
  become: true
  block:
    - name: Check if per-project runners are already registered
      stat:
        path: /etc/gitlab-runner/registration/project.{{ item.id }}.json
      loop: "{{ gitlab_macos_projects }}"
      loop_control:
        label: "{{ item.name }}"
        index_var: index
      register: runner_registered

    - name: Register per-project runners
      gitlab_runner:
        description: "{{ gitlab_runner_description }}"
        api_token: "{{ item.access_token | trim }}"
        registration_token: "{{ item.registration_token | trim }}"
        project: "{{ item.id }}"
        access_level: not_protected
        api_url: https://gitlab.com/
        state: present
        active: true
        tag_list: "{{ runner_tags }}"
        run_untagged: false
        locked: false
      loop: "{{ gitlab_macos_projects }}"
      loop_control:
        label: "{{ item.name }}"
        index_var: index
      when: not runner_registered.results[index].stat.exists
      register: runner_registration

    - name: Record per-project runner registrations
      copy:
        content: "{{ runner_registration.results[index].runner }}"
        dest: /etc/gitlab-runner/registration/project.{{ item.id }}.json
        owner: root
        group: admin
        mode: 'u=rw,g=,o='
      loop: "{{ gitlab_macos_projects }}"
      loop_control:
        label: "{{ item.name }}"
        index_var: index
      when: not runner_registered.results[index].stat.exists

    - name: Read per-project runner registrations
      shell:
        cmd: jq --slurp '.' project.*.json
        chdir: /etc/gitlab-runner/registration
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
      register: runner_per_project_registrations_raw
      changed_when: false

    - name: Set runner_per_project_registrations
      set_fact:
        runner_per_project_registrations: "{{ runner_per_project_registrations_raw.stdout | from_json }}"

- name: Create runner config file
  become: true
  template:
    src: config.toml
    dest: /etc/gitlab-runner/config.toml
    owner: root
    group: admin
    mode: 'u=rw,g=,o='
