---

- name: Set daemon config file path
  set_fact:
    runner_daemon_config_path: /Library/LaunchDaemons/{{ runner_service_label }}.plist

- name: Create daemon config file
  become: true
  template:
    src: launch-daemon.xml
    dest: "{{ runner_daemon_config_path }}"
    owner: root
    group: wheel
    mode: 'u=rw,g=r,o=r'

- name: Enable daemon
  become: true
  command: launchctl enable system/{{ runner_service_label }}

- name: Start Daemon
  become: true
  command: launchctl bootstrap system {{ runner_daemon_config_path }}
