---

- name: Is the daemon present?
  command: launchctl print system/{{ runner_service_label }}
  changed_when: false
  ignore_errors: true
  register: launchctl_list_cmd

- name: Set runner_daemon_present
  set_fact:
    runner_daemon_present: "{{ launchctl_list_cmd.rc == 0}}"
    runner_daemon_pid: 0

- name: Set runner_daemon_pid 1 / 2
  set_fact:
    runner_daemon_pid_raw: "{{ launchctl_list_cmd.stdout | regex_search('\\s+pid\\s+=\\s+([0-9]+)', '\\1') }}"
  when: runner_daemon_present

- name: Set runner_daemon_pid 2 / 2
  set_fact:
    runner_daemon_pid: "{{ runner_daemon_pid_raw | first }}"
  when: runner_daemon_present and (runner_daemon_pid_raw is iterable) and (runner_daemon_pid_raw is sequence) and not (runner_daemon_pid_raw is string)

- name: Disable daemon
  become: true
  command: launchctl disable system/{{ runner_service_label }}
  when: runner_daemon_present

- name: Tell daemon to perform a graceful shutdown
  become: true
  command: launchctl kill SIGQUIT system/{{ runner_service_label }}
  when: runner_daemon_pid != 0

- name: Wait for daemon to quit
  shell:
    cmd: |
      while true; do
        ps -p {{ runner_daemon_pid }}
        PS_STATUS=$?
        if [[ $PS_STATUS -ne 0 ]]; then
          exit 0
        fi
        sleep 5
      done
  when: runner_daemon_pid != 0

- name: Pause before removing daemon
  command: sleep 10
  changed_when: false
  when: runner_daemon_pid != 0

- name: Remove daemon
  become: true
  command: launchctl bootout system/{{ runner_service_label }}
  when: runner_daemon_present
