---

- name: Set escaped runner service line regex
  set_fact:
    runner_service_line_regex: "{{ '([-0-9]+)\\s+([0-9]+)\\s+' + (runner_service_label | regex_escape) }}"

- name: Read the list of launchd services
  command: launchctl list
  register: launchctl_list
  changed_when: false

- name: Find the runner service
  set_fact:
    runner_service_line: "{{ launchctl_list.stdout | default('') | regex_search(runner_service_line_regex) | default('') }}"

- name: Stop daemon
  become: true
  community.general.launchd:
    name: "{{ runner_service_label }}"
    state: stopped
  when: runner_service_line != ""
