---

- name: Stop daemon, if necessary
  import_tasks: tasks/stop-daemon.yaml

- name: Read the list of registered VMs
  become: true
  command: prlctl list --all --output name --no-header
  register: vm_list
  changed_when: false

- name: Stop all VMs
  become: true
  command: prlctl stop {{ item }}
  loop: "{{ vm_list.stdout_lines }}"
  ignore_errors: true

- name: Unregister all VMs
  become: true
  command: prlctl unregister {{ item }}
  loop: "{{ vm_list.stdout_lines }}"

- name: Retrieve user list
  become: true
  command: prlsrvctl user list --output name,def_vm_home --no-header
  register: parallels_user_list
  changed_when: false

- name: Get default VM path
  set_fact:
    root_parallels_home: "{{ parallels_user_list.stdout | regex_search('root@\\.\\s+([^\\s]+)', '\\1') | first }}"

- name: Unregister owned runner
  become: true
  gitlab_runner:
    description: "{{ gitlab_runner_description }}"
    api_token: "{{ gitlab_runner_access_token | trim }}"
    owned: true
    state: absent
  ignore_errors: true

- name: Delete runner files & directories
  become: true
  file:
    dest: "{{ item }}"
    state: absent
  loop:
    - /etc/gitlab-runner
    - /usr/local/bin/gitlab-runner
    - /var/gitlab-runner
    - /var/log/gitlab-runner
    - "{{ runner_daemon_config_path }}"
    - "{{ root_parallels_home }}"
