# macOS Gitlab Runner configuration.

# Global
concurrent = 1
check_interval = 15
log_level = "debug"

# [session_server]
#   session_timeout = 1800

{% for item in gitlab_macos_projects %}
[[runners]]
  name = "{{ item.name }}"
  url = "https://gitlab.com/"
  token = "{{ runner_per_project_registrations[loop.index-1].token }}"
  builds_dir = "/Users/{{ gitlab_executor.username }}/builds"
  cache_dir = "/Users/{{ gitlab_executor.username }}/caches"
  executor = "parallels"

  pre_clone_script = '''
    echo "Preparing Keychain"

    KEYCHAIN="/Users/{{ gitlab_executor.username }}/Library/Keychains/{{ gitlab_executor.keychain_name }}"
    KEYCHAIN_PASSWORD="{{ gitlab_executor.keychain_password | trim }}"

    security unlock-keychain -p "${KEYCHAIN_PASSWORD}" "${KEYCHAIN}"
    security list-keychains -s "${KEYCHAIN}" "/Library/Keychains/System.keychain"
  '''

  pre_build_script = '''
    echo "Creating runner variables"

    source ~/bin/setup-job-variables.sh
  '''

  [runners.parallels]
    base_name = "{{ gitlab_executor.vm_name }}"
    disable_snapshots = false

  [runners.ssh]
    user = "{{ gitlab_executor.username }}"
    password = "{{ gitlab_executor.password | trim }}"
    disable_strict_host_key_checking = true
{% endfor %}
