# macOS Gitlab Runner configuration.

# Global
concurrent = 1
check_interval = 15
log_level = "warn"

# [session_server]
#   session_timeout = 1800

[[runners]]
  name = "{{ gitlab_runner_description }}"
  url = "https://gitlab.com/"
  token = "{{ runner_owned_registration.token }}"
  builds_dir = "/Users/{{ gitlab_executor.username }}/builds"
  cache_dir = "/Users/{{ gitlab_executor.username }}/caches"
  executor = "parallels"

  pre_clone_script = '''
    echo "Running pre-clone script"

    # This script is provided by the executor VM.
    KEYCHAIN_PASSWORD="{{ gitlab_executor.keychain_password | trim }}" ~/bin/pre-clone.sh
  '''

  pre_build_script = '''
    echo "Running pre-build script"

    # This script is provided by the executor VM.
    source ~/bin/pre-build.sh
  '''

  [runners.parallels]
    base_name = "{{ gitlab_executor.vm_name }}"
    disable_snapshots = false

  [runners.ssh]
    user = "{{ gitlab_executor.username }}"
    password = "{{ gitlab_executor.password | trim }}"
    disable_strict_host_key_checking = true
