# macOS Gitlab Runner configuration.

# Global
concurrent = 1
check_interval = 60
log_level = "warn"

# [session_server]
#   session_timeout = 1800

{% for item in gitlab_macos_projects %}
[[runners]]
  name = "{{ item.name }}"
  url = "https://gitlab.com/"
  token = "{{ runner_per_project_registrations[loop.index-1].token }}"
  builds_dir = "/Users/{{ runner_user }}/builds"
  cache_dir = "/Users/{{ runner_user }}/caches"
  executor = "parallels"

  [runners.parallels]
    base_name = "{{ gitlab_executor.vm_name }}"
    disable_snapshots = false

  [runners.ssh]
    user = "{{ gitlab_executor.user }}"
    password = "{{ gitlab_executor.password | trim }}"
{% endfor %}
