---

- name: Provision Per-User Resources
  hosts: all
  gather_facts: false
  tasks:

    - name: Read the list of VMs
      command: prlctl list --all --output name
      register: prlctl_list
      changed_when: false

    - name: Is the executor VM registered?
      set_fact:
        is_vm_registered: "{{ '{{' }} prlctl_list.stdout.find(vm_name) != -1 {{ '}}' }}"

    - name: Register the executor VM
      command: prlctl register /Users/{{ runner_user }}/Parallels/{{ '{{' }} vm_name {{ '}}' }}.pvm
      when: not is_vm_registered
