---
- hosts: all
  environment:
    PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
  tasks:
    - name: Set daemon config file path
      set_fact:
        runner_daemon_config_path: /Library/LaunchDaemons/{{ gitlab_runner_daemon_label }}.plist
    
    - name: Install
      include_tasks: tasks/install.yaml
      when: not uninstall_runner

    - name: Uninstall
      include_tasks: tasks/uninstall.yaml
      when: uninstall_runner

  handlers:
    - name: Clean up downloaded VM
      become: true
      file:
        dest: /tmp/{{ gitlab_executor.vm_name }}.tgz
        state: absent
      listen: cleanup-downloaded-vm
