---
- hosts: all
  # become: true
  tasks:

    - name: Disable Sleep
      import_tasks: tasks/no-sleep.yaml
      when: disable_sleep

    - name: Disable Software Updates
      import_role:
        name: disable-software-updates
      when: disable_software_updates

    - name: Install Homebrew
      import_role:
        name: install-homebrew

    - name: Install Homebrew packages
      community.general.homebrew:
        name: "{{ item }}"
      loop:
        - ansible
        - coreutils

    - name: Install Pip Packages
      become: true
      ansible.builtin.pip:
        name: "{{ item }}"
      loop:
        - python-gitlab==3.6.0

    - name: Create Runner
      import_tasks: tasks/runner.yaml

  handlers:
    - name: Clean up gitlab-runner temp directory
      become: true
      file:
        dest: /Users/{{ runner_user }}/.temp/
        state: absent
      listen: clean-runner-temp-dir
